# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4554f398fd63ee6e5166d82b4cf138fe0c2c6734c064fcff0ec2d7d49d8f824f2e4162798468dd19b45c8d1c1f32df1fe6131f6500f0ae6cdeb4f52289cf856d

test:
  secret_key_base: a94da836dc77b2531f752301d45f560391b591ea0473c4c55813532e4a63d3b8b11204f7de62d960fd9079faca1ffb854e50b25928fbbea77a3cc9d9259387fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
